### ISSUE TITLE
Requirements.txt is missing some requirements

### ISSUE THREAD

**Issue by JesseCrocker** [kylebarron/landsat-cogeo-mosaic#16]
After running ` pip3 install landsat-cogeo-mosaic` i expect to be able to run `landsat-cogeo-mosaic`, but i also had to install geopandas and keplergl_cli before it would work.

**Comment by kylebarron** [comment]
You have to run `pip install landsat-cogeo-mosaic[cli]` to install the extra packages for the CLI. I'll update the docs
